import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header/page";
import Footer from "./components/Footer/Footer";
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import  { Toaster } from 'react-hot-toast';
import { ModalProvider } from "@/components/provider/modal-provider";
import Bot from "./components/Bot/Bot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ModalProvider/>
        <html lang="en">
          <body className={inter.className}>
            <Header />
                      {children}
                      <Footer />
                      <Toaster/>
                      <Bot />s
                      </body>
                      
        </html>
    </ClerkProvider>
    
  );
}
